### ISSUE TITLE
Unable to login with fresh clean install

### ISSUE THREAD

**Issue by Kimbaras** [openpim/server#22]
Hey there!

So, I've tried to spin up an instance (self-hosted in my homelab), followed the docs. managed to get the container up and running but when trying to login for the first time I get an error as shown in the screen attached

![error](https://github.com/openpim/server/assets/102742484/f733ff1a-1f60-4ad4-b612-601c0f0f38a6)

And this in the container logs

`[20/Oct/2023:20:01:25 +0000] "GET /favicon.ico HTTP/1.1" 200 4286 "http://<openpim ip>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
2023/10/20 20:01:29 [error] 18#18: *15 connect() failed (111: Connection refused) while connecting to upstream, client: <my pc ip>, server: _, request: "POST /graphql HTTP/1.1", upstream: "http://127.0.0.1:8080/graphql", host: "<openpim ip>", referrer: "http://<openpim ip>/"
<my pc ip> - - [20/Oct/2023:20:01:29 +0000] "POST /graphql HTTP/1.1" 502 575 "http://<openpim ip>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"`

Any idea of what is wrong here?

Thanks!

**Comment by Kimbaras** [comment]
> Hi,
> 
> Please take a look at the docker logs during container start. You should see some errors there related to the server.

@openpim yes, the errors are already provided in the original post, in particular, this bit

`failed (111: Connection refused) while connecting to upstream, client:`

seems the culprit, but not really sure where / what it's missing.
I've seen that error previously when working directly with Apache2 (or Nginx, can't remember which one) due to a misconfiguration of the webserver, so it's seem there is something wrong in the config of the docker image (I'd imagine)

Thanks

**Comment by openpim** [comment]
it should be more output in the log. But there is another way. You can execute the command

sudo docker exec -it <container id> /bin/bash

where <container id> is the id of container where OpenPIM is running. So you will start the shell script inside the container and there you can execute the command:

cat server.log

to see the output of the server log. There should be some addition information

**Comment by Kimbaras** [comment]
Ok, seems there are issues while connecting to the database 

`2023/11/09 10:00:38.569 [info]:  Arguments: /usr/local/bin/node,/server/dist/src/index.js 
(sequelize) Warning: PostgresSQL does not support 'INTEGER' with LENGTH, UNSIGNED or ZEROFILL. Plain 'INTEGER' will be used instead. 
>> Check: http://www.postgresql.org/docs/9.4/static/datatype.html
/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:130
                reject(new sequelizeErrors.ConnectionRefusedError(err));
                       ^
ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:5432
    at Client._connectionCallback (/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:130:24)
    at Client._handleErrorWhileConnecting (/server/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorEvent (/server/node_modules/pg/lib/client.js:315:19)
    at Connection.emit (node:events:513:28)
    at Socket.reportStreamError (/server/node_modules/pg/lib/connection.js:52:12)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  parent: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432
  },
  original: Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 5432`

And by looking again at the logs, seems there was some issues during the import of the init.sql step of the docs, maybe some permission missing on the dedicated user?
Will try a different way later today, but are there any specific requirements / instructions for this part?

Thanks!

**Comment by Kimbaras** [comment]
Oh wait... 
Just realized that I'm getting a different error of the initial one... 
In this case the login screen is not even showing up...

Further troubleshooting then

**Comment by Kimbaras** [comment]
Success!

I was finally able to start it and using it.
The main issues were permissions on the database, in particular 

`2023/11/09 10:24:25.238 [info]:  Running a GraphQL API server at http://localhost:8080/graphql 
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error
    at Query.run (/server/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /server/node_modules/sequelize/lib/sequelize.js:313:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.select (/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:396:12)
    at async Function.findAll (/server/node_modules/sequelize/lib/model.js:1128:21)
    at async ModelsManager.initLanguages (/server/dist/src/models/manager.js:397:27)
    at async ModelsManager.initModels (/server/dist/src/models/manager.js:233:9)
    at async ModelsManager.init (/server/dist/src/models/manager.js:226:9) {
  name: 'SequelizeDatabaseError',
  parent: error: permission denied for table languages
      at Parser.parseErrorMessage (/server/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/server/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/server/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/server/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 97,
    severity: 'ERROR',
    code: '42501',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'aclchk.c',
    line: '3447',
    routine: 'aclcheck_error',
    sql: 'SELECT "identifier", "name", "id", "tenantId", "createdBy", "updatedBy", "createdAt", "updatedAt", "deletedAt" FROM "languages" AS "Language" WHERE ("Language"."deletedAt" IS NULL) ORDER BY "Language"."tenantId" DESC, "Language"."id" ASC;',
    parameters: undefined
  },
  original: error: permission denied for table languages
      at Parser.parseErrorMessage (/server/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/server/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/server/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/server/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 97,
    severity: 'ERROR',
    code: '42501',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'aclchk.c',
    line: '3447',
    routine: 'aclcheck_error',
    sql: 'SELECT "identifier", "name", "id", "tenantId", "createdBy", "updatedBy", "createdAt", "updatedAt", "deletedAt" FROM "languages" AS "Language" WHERE ("Language"."deletedAt" IS NULL) ORDER BY "Language"."tenantId" DESC, "Language"."id" ASC;',
    parameters: undefined
  },
  sql: 'SELECT "identifier", "name", "id", "tenantId", "createdBy", "updatedBy", "createdAt", "updatedAt", "deletedAt" FROM "languages" AS "Language" WHERE ("Language"."deletedAt" IS NULL) ORDER BY "Language"."tenantId" DESC, "Language"."id" ASC;',
  parameters: {}
}
`

I've used the default postgres user and that seemed to work.
This means that the "standard" procedure of creating the database and a dedicated user, along with "grant all privileges" is not enough.
I believe it's worth mentioning that on the docs? That basically a "superuser" is required, at least from what I understand.

Beside this, feel free to close this one as completed!

Thanks for the support!

**Comment by amirukg** [comment]
if you have PG installed and ,running docker on the same machine try to use host.docker.internal instead of 127.0.0.1 or localhost
example:
docker run -d -p 80:80 -v [path to file storage]:/filestorage --env OPENPIM_DATABASE_ADDRESS=host.docker.internal --env OPENPIM_DATABASE_NAME=[database name] --env OPENPIM_DATABASE_USER=[database user] --env OPENPIM_DATABASE_PASSWORD=[database password] openpim/production:2.0

**Comment by MindDesign** [comment]
I also got an error when logging in on a fresh install telling me the user was not authenticated, and I remained on the login screen. But the docker logs said

`User admin was logged on. Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGVuYW50SWQiOiJkZWZhdWx0IiwibG9naW4iOiJhZG1pbiIsImlhdCI6MTcyNzk0NjU4NywiZXhwIjoxNzI4MDMyOTg3fQ.07CUVDYv3bBsSYCwpmHXoSUSUTp75xX1qVA5k3ipFiE `

Just had to manually go to the dashboard.

**Comment by SebastiaanDenHertog** [comment]
For me, it was that he could not access the database. Just check the username and password and the pg_hba.conf file.

**Comment by OhtuIT** [comment]
I am having this same issue with a new install on Ubuntu 24.04:

<img width="663" height="629" alt="Image" src="https://github.com/user-attachments/assets/7f39ec1e-6ccc-4235-8435-51b91c3ec7bd" />

I was starting the container on port 8080 and I thought that was teh issue but even after just starting on Port 80 the issue persists. I don't have access to the logs right now but it mentioned something like "access denied for 127.0.0.1:8080 graphql". I will have access to the actual logs tomorrow.

After reading the comments here, it looks like it had something to do with Postgres but I have changed postgresql.conf to listen to '*' and also added the host all all 0.0.0.0 md5 line to pg_hba.conf. I have tried applying init.sql to the postgres db using the default postgres user and I still get the same error. I created a new db called openpim with a new user openpim with all privileges and also applied init.sql and I still get the same error.

Any help would be greatly appreciated.
